create table if not exists public.menu_option_groups (
  id bigint generated by default as identity primary key,
  idloja bigint not null references public.lojas (idloja) on delete cascade,
  titulo text not null,
  tipo text not null default 'extra',
  obrigatorio boolean not null default false,
  max_selecoes integer not null default 1,
  ativo boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_option_items (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.menu_option_groups (id) on delete cascade,
  nome text not null,
  preco numeric(10, 2) not null default 0,
  default_selected boolean not null default false,
  ativo boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_option_group_links (
  id bigint generated by default as identity primary key,
  idmenu bigint not null references public.menus (idmenu) on delete cascade,
  grupo_id bigint not null references public.menu_option_groups (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint menu_option_group_links_unique unique (idmenu, grupo_id)
);

create index if not exists idx_menu_option_groups_loja on public.menu_option_groups (idloja);
create index if not exists idx_menu_option_items_group on public.menu_option_items (grupo_id);
create index if not exists idx_menu_option_group_links_menu on public.menu_option_group_links (idmenu);
create index if not exists idx_menu_option_group_links_group on public.menu_option_group_links (grupo_id);
