-- Fase 0 do dispatch interno de estafetas (substituto do Shipday).
-- Tabela de estafetas, ligada a um utilizador existente (mesmo padrao de lojas.idutilizador).

create table if not exists public.estafetas (
  id bigint generated by default as identity primary key,
  idutilizador integer not null references public.utilizadores(idutilizador),
  nome text not null,
  telefone text,
  email text,
  veiculo text not null default 'mota' check (veiculo in ('bicicleta', 'mota', 'carro', 'a_pe')),
  matricula text,
  foto_url text,
  ativo boolean not null default false,
  disponivel boolean not null default false,
  online boolean not null default false,
  ultima_localizacao_lat double precision,
  ultima_localizacao_lng double precision,
  ultima_localizacao_em timestamptz,
  ultima_atividade_em timestamptz,
  avaliacao_media numeric not null default 5 check (avaliacao_media between 0 and 5),
  total_entregas integer not null default 0,
  total_ganhos numeric not null default 0,
  pedido_atual_id bigint references public.orders(id),
  password_temporaria boolean not null default false,
  eliminado boolean not null default false,
  eliminado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (idutilizador)
);

comment on table public.estafetas is 'Estafetas (carreteiros) internos do PedeJa. Substitui o registo de carriers do Shipday.';

create index if not exists idx_estafetas_disponivel on public.estafetas (ativo, disponivel, online) where eliminado = false;
create index if not exists idx_estafetas_pedido_atual on public.estafetas (pedido_atual_id) where pedido_atual_id is not null;

alter table public.estafetas enable row level security;
-- Sem policies diretas: tal como orders/deliveries, todo o acesso passa por RPCs
-- SECURITY DEFINER (padrao ja usado em orders_apply_authorized_patch).
