-- Fase 0 do dispatch interno de estafetas.
-- Registo de auditoria/ganhos de cada atribuicao de um pedido a um estafeta.
-- NAO duplica a maquina de estados: orders.estado_interno continua a ser a
-- unica fonte de verdade sobre o estado do pedido (ver orderStatusMapper.js).

create table if not exists public.atribuicoes_entrega (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id),
  estafeta_id bigint not null references public.estafetas(id),
  ativo boolean not null default true,
  atribuido_em timestamptz not null default now(),
  aceite_em timestamptz,
  recolhido_em timestamptz,
  a_caminho_em timestamptz,
  entregue_em timestamptz,
  cancelado_em timestamptz,
  rejeitado_em timestamptz,
  motivo_cancelamento text,
  distancia_km numeric,
  valor_estafeta numeric,
  reatribuido_de_id bigint references public.estafetas(id),
  reatribuido_para_id bigint references public.estafetas(id),
  criado_em timestamptz not null default now()
);

comment on table public.atribuicoes_entrega is 'Auditoria de atribuicoes de pedidos a estafetas (quem foi atribuido/aceitou/rejeitou/ganhou quanto). O estado do pedido em si vive em orders.estado_interno.';

create index if not exists idx_atribuicoes_order on public.atribuicoes_entrega (order_id);
create index if not exists idx_atribuicoes_estafeta on public.atribuicoes_entrega (estafeta_id);
create unique index if not exists uq_atribuicoes_order_ativa on public.atribuicoes_entrega (order_id) where ativo = true;

alter table public.atribuicoes_entrega enable row level security;
-- Sem policies diretas: acesso via RPCs SECURITY DEFINER (ver 028_estafeta_dispatch_rpcs.sql).

-- Flag de ativacao do dispatch interno por loja. Default false: nenhuma loja
-- e afetada ate ser explicitamente ligada (rollout gradual, loja a loja).
alter table public.lojas add column if not exists dispatch_interno_ativo boolean not null default false;
comment on column public.lojas.dispatch_interno_ativo is 'Quando true, novos pedidos desta loja usam o dispatch de estafetas interno (atribuicoes_entrega) em vez do Shipday.';
