-- Fase 4 (parcial): notificacoes push reais para o estafeta quando lhe e
-- atribuido um pedido, em vez de depender so do polling a cada 8s.

create extension if not exists pg_net;

create table if not exists public.estafeta_push_subscriptions (
  id bigint generated by default as identity primary key,
  idutilizador integer not null references public.utilizadores(idutilizador),
  endpoint text not null unique,
  subscription jsonb not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create index if not exists idx_estafeta_push_idutilizador on public.estafeta_push_subscriptions (idutilizador) where ativo = true;

alter table public.estafeta_push_subscriptions enable row level security;
-- Sem policies diretas: acesso via RPCs SECURITY DEFINER, mesmo padrao das restantes tabelas novas.

create or replace function public.estafeta_save_push_subscription(caller_user_id integer, subscription_input jsonb)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_endpoint text;
begin
  v_endpoint := subscription_input->>'endpoint';
  if v_endpoint is null or v_endpoint = '' then
    raise exception 'Subscription sem endpoint valido.' using errcode = '22023';
  end if;

  insert into public.estafeta_push_subscriptions (idutilizador, endpoint, subscription, ativo)
  values (caller_user_id, v_endpoint, subscription_input, true)
  on conflict (endpoint) do update set
    idutilizador = excluded.idutilizador,
    subscription = excluded.subscription,
    ativo = true;
end;
$function$;

create or replace function public.estafeta_remove_push_subscription(caller_user_id integer, endpoint_input text)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
begin
  update public.estafeta_push_subscriptions
  set ativo = false
  where endpoint = endpoint_input and idutilizador = caller_user_id;
end;
$function$;

revoke all on function public.estafeta_save_push_subscription(integer, jsonb) from public;
revoke all on function public.estafeta_remove_push_subscription(integer, text) from public;
grant execute on function public.estafeta_save_push_subscription(integer, jsonb) to anon, authenticated, postgres, service_role;
grant execute on function public.estafeta_remove_push_subscription(integer, text) to anon, authenticated, postgres, service_role;

-- Notifica (fire-and-forget via pg_net) o estafeta assim que lhe e atribuido
-- um pedido, chamando a edge function send-push-notification. Nao bloqueia
-- nem falha a atribuicao se o push nao chegar a sair.
create or replace function public.notify_estafeta_new_assignment(estafeta_id_input bigint, order_id_input bigint)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_idutilizador integer;
  v_endereco text;
  v_valor numeric;
begin
  select e.idutilizador into v_idutilizador from public.estafetas e where e.id = estafeta_id_input;
  if v_idutilizador is null then
    return;
  end if;

  select o.customer_address, o.taxa_entrega into v_endereco, v_valor from public.orders o where o.id = order_id_input;

  begin
    perform net.http_post(
      url := 'https://zvsuirjjpqfvqfrbotdc.supabase.co/functions/v1/send-push-notification',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2c3VpcmpqcHFmdnFmcmJvdGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NzQ4NjIsImV4cCI6MjA4NDE1MDg2Mn0.0R06_LiJCzqqJUpchvZo_U1n_qEhawPhmfGufjYfW04'
      ),
      body := jsonb_build_object(
        'idutilizador', v_idutilizador,
        'title', '🔔 Novo pedido disponível',
        'body', coalesce(v_endereco, 'Novo pedido') || ' — ' || coalesce(v_valor::text, '0') || '€',
        'url', '/estafeta'
      ),
      timeout_milliseconds := 5000
    );
  exception when others then
    -- Nunca deixar uma falha de push (pg_net indisponivel, edge function em
    -- baixo, etc.) rebentar a atribuicao do pedido em si.
    null;
  end;
end;
$function$;

revoke all on function public.notify_estafeta_new_assignment(bigint, bigint) from anon, authenticated;

-- Liga a notificacao ao momento exato em que um pedido e atribuido
-- (manual ou automatico), reaproveitando o unico ponto de mutacao existente.
create or replace function public._assign_delivery_unchecked(
  order_id_input bigint,
  estafeta_id_input bigint,
  distancia_km_input numeric
) returns public.atribuicoes_entrega
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_order public.orders;
  v_estafeta public.estafetas;
  v_assignment public.atribuicoes_entrega;
begin
  select * into v_order from public.orders where id = order_id_input for update;
  if v_order is null then
    raise exception 'Pedido nao encontrado.' using errcode = 'P0002';
  end if;

  select * into v_estafeta from public.estafetas where id = estafeta_id_input for update;
  if v_estafeta is null or v_estafeta.eliminado or not v_estafeta.ativo then
    raise exception 'Estafeta invalido ou inativo.' using errcode = '42501';
  end if;

  if exists(select 1 from public.atribuicoes_entrega where order_id = order_id_input and ativo = true) then
    raise exception 'Este pedido ja tem um estafeta atribuido.' using errcode = 'P0002';
  end if;

  insert into public.atribuicoes_entrega (order_id, estafeta_id, distancia_km, valor_estafeta)
  values (order_id_input, estafeta_id_input, distancia_km_input, coalesce(v_order.taxa_entrega, 0))
  returning * into v_assignment;

  update public.orders set
    estado_interno = case when estado_interno in ('pendente', 'aceite') then 'atribuindo_estafeta' else estado_interno end,
    driver_name = v_estafeta.nome,
    driver_phone = v_estafeta.telefone,
    veiculo_estafeta = v_estafeta.veiculo,
    atribuido_em = now(),
    updated_at = now()
  where id = order_id_input;

  update public.estafetas set
    disponivel = false,
    pedido_atual_id = order_id_input,
    atualizado_em = now()
  where id = estafeta_id_input;

  perform public.notify_estafeta_new_assignment(estafeta_id_input, order_id_input);

  return v_assignment;
end;
$function$;

revoke all on function public._assign_delivery_unchecked(bigint, bigint, numeric) from public;
revoke execute on function public._assign_delivery_unchecked(bigint, bigint, numeric) from anon, authenticated;
