-- Fase 4 (backlog): avaliacoes do cliente ao estafeta apos entrega.

create table if not exists public.avaliacoes_estafeta (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) unique,
  estafeta_id bigint not null references public.estafetas(id),
  customer_user_id text,
  classificacao integer not null check (classificacao between 1 and 5),
  comentario text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_avaliacoes_estafeta_id on public.avaliacoes_estafeta (estafeta_id);

alter table public.avaliacoes_estafeta enable row level security;
-- Sem policies diretas: acesso via RPCs SECURITY DEFINER, mesmo padrao das restantes tabelas novas.

create or replace function public.customer_rate_delivery(
  caller_user_id integer,
  order_id_input bigint,
  classificacao_input integer,
  comentario_input text default null
) returns public.avaliacoes_estafeta
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_order public.orders;
  v_estafeta_id bigint;
  v_avaliacao public.avaliacoes_estafeta;
  v_media numeric;
begin
  if classificacao_input is null or classificacao_input < 1 or classificacao_input > 5 then
    raise exception 'A classificacao deve ser entre 1 e 5.' using errcode = '22023';
  end if;

  select * into v_order from public.orders where id = order_id_input;
  if v_order is null then
    raise exception 'Pedido nao encontrado.' using errcode = 'P0002';
  end if;

  if v_order.customer_user_id is distinct from caller_user_id::text then
    raise exception 'Sem permissao para avaliar este pedido.' using errcode = '42501';
  end if;

  if v_order.estado_interno <> 'entregue' then
    raise exception 'So podes avaliar depois de o pedido ser entregue.' using errcode = 'P0002';
  end if;

  select estafeta_id into v_estafeta_id
  from public.atribuicoes_entrega
  where order_id = order_id_input and entregue_em is not null
  order by entregue_em desc
  limit 1;

  if v_estafeta_id is null then
    raise exception 'Este pedido nao tem um estafeta interno associado para avaliar.' using errcode = 'P0002';
  end if;

  insert into public.avaliacoes_estafeta (order_id, estafeta_id, customer_user_id, classificacao, comentario)
  values (order_id_input, v_estafeta_id, caller_user_id::text, classificacao_input, nullif(trim(comentario_input), ''))
  on conflict (order_id) do update set
    classificacao = excluded.classificacao,
    comentario = excluded.comentario,
    atualizado_em = now()
  returning * into v_avaliacao;

  select avg(classificacao) into v_media from public.avaliacoes_estafeta where estafeta_id = v_estafeta_id;

  update public.estafetas set avaliacao_media = round(coalesce(v_media, 5), 2), atualizado_em = now()
  where id = v_estafeta_id;

  return v_avaliacao;
end;
$function$;

create or replace function public.get_my_delivery_rating(caller_user_id integer, order_id_input bigint)
returns public.avaliacoes_estafeta
language sql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  select a.* from public.avaliacoes_estafeta a
  join public.orders o on o.id = a.order_id
  where a.order_id = order_id_input and o.customer_user_id = caller_user_id::text
  limit 1;
$$;

revoke all on function public.customer_rate_delivery(integer, bigint, integer, text) from public;
revoke all on function public.get_my_delivery_rating(integer, bigint) from public;
grant execute on function public.customer_rate_delivery(integer, bigint, integer, text) to anon, authenticated, postgres, service_role;
grant execute on function public.get_my_delivery_rating(integer, bigint) to anon, authenticated, postgres, service_role;
