-- Fase 1.7 (reestruturacao base44): avaliacoes do cliente ao pedido/restaurante,
-- distintas de avaliacoes_estafeta (essa e so sobre o estafeta). Mesmo padrao
-- de tabela+RPCs SECURITY DEFINER usado em 035_avaliacoes_estafeta.sql.

create table if not exists public.avaliacoes_pedido (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) unique,
  loja_id bigint not null references public.lojas(idloja),
  customer_user_id text,
  classificacao integer not null check (classificacao between 1 and 5),
  comentario text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_avaliacoes_pedido_loja on public.avaliacoes_pedido (loja_id);

alter table public.avaliacoes_pedido enable row level security;
-- Sem policies diretas: acesso via RPCs SECURITY DEFINER, mesmo padrao das restantes tabelas novas.

create or replace function public.customer_rate_order(
  caller_user_id integer,
  order_id_input bigint,
  classificacao_input integer,
  comentario_input text default null
) returns public.avaliacoes_pedido
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
declare
  v_order public.orders;
  v_avaliacao public.avaliacoes_pedido;
begin
  if classificacao_input is null or classificacao_input < 1 or classificacao_input > 5 then
    raise exception 'A classificacao deve ser entre 1 e 5.' using errcode = '22023';
  end if;

  select * into v_order from public.orders where id = order_id_input;
  if v_order is null then
    raise exception 'Pedido nao encontrado.' using errcode = 'P0002';
  end if;

  if v_order.customer_user_id is distinct from caller_user_id::text then
    raise exception 'Sem permissao para avaliar este pedido.' using errcode = '42501';
  end if;

  if v_order.estado_interno <> 'entregue' then
    raise exception 'So podes avaliar depois de o pedido ser entregue.' using errcode = 'P0002';
  end if;

  insert into public.avaliacoes_pedido (order_id, loja_id, customer_user_id, classificacao, comentario)
  values (order_id_input, v_order.loja_id, caller_user_id::text, classificacao_input, nullif(trim(comentario_input), ''))
  on conflict (order_id) do update set
    classificacao = excluded.classificacao,
    comentario = excluded.comentario,
    atualizado_em = now()
  returning * into v_avaliacao;

  return v_avaliacao;
end;
$function$;

create or replace function public.get_my_order_rating(caller_user_id integer, order_id_input bigint)
returns public.avaliacoes_pedido
language sql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  select a.* from public.avaliacoes_pedido a
  join public.orders o on o.id = a.order_id
  where a.order_id = order_id_input and o.customer_user_id = caller_user_id::text
  limit 1;
$$;

create or replace function public.admin_list_order_reviews(caller_user_id integer)
returns table (
  id bigint,
  order_id bigint,
  loja_id bigint,
  loja_nome text,
  customer_nome text,
  classificacao integer,
  comentario text,
  criado_em timestamptz
)
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
begin
  if not public.is_platform_admin(caller_user_id) then
    raise exception 'Apenas administradores podem ver as avaliacoes.' using errcode = '42501';
  end if;

  return query
  select
    ap.id,
    ap.order_id,
    ap.loja_id,
    l.nome::text as loja_nome,
    o.customer_nome::text,
    ap.classificacao,
    ap.comentario,
    ap.criado_em
  from public.avaliacoes_pedido ap
  join public.lojas l on l.idloja = ap.loja_id
  join public.orders o on o.id = ap.order_id
  order by ap.criado_em desc;
end;
$function$;

revoke all on function public.customer_rate_order(integer, bigint, integer, text) from public;
revoke all on function public.get_my_order_rating(integer, bigint) from public;
revoke all on function public.admin_list_order_reviews(integer) from public;
grant execute on function public.customer_rate_order(integer, bigint, integer, text) to anon, authenticated, postgres, service_role;
grant execute on function public.get_my_order_rating(integer, bigint) to anon, authenticated, postgres, service_role;
grant execute on function public.admin_list_order_reviews(integer) to anon, authenticated, postgres, service_role;
